config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :categories do
    resources :deals
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :deals, dependent: :destroy
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories, dependent: :destroy
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :deals, foreign_key: :user_id, class_name: 'Deal', dependent: :destroy
  has_many :categories, foreign_key: :user_id, class_name: 'Category', dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]
  before_action :validate_checkbox, only: [:create]

  # GET /deals or /deals.json
  def index
    @deals = current_user.deals
  end

  # GET /deals/1 or /deals/1.json
  def show; end

  # GET /deals/new
  def new
    @deal = Deal.new
    @categories = current_user.categories
  end

  # GET /deals/1/edit
  def edit; end

  # POST /deals or /deals.json
  def create
    @deal = current_user.deals.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to categories_path, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deal_url(@deal), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to category_url(params[:category_id]), notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:name, :amount, category_ids: [])
  end

  def validate_checkbox
    return unless params[:deal][:category_ids].length == 1

    flash[:alert] = 'Please select at least one category.'
    redirect_to new_category_deal_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= bootstrap_form_for(@category) do |f| %>
    <%= f.text_field :name, wrapper: { class: 'text-primary' } %>
    <%= f.text_field :icon, wrapper: { class: 'text-primary' } %>
    <div class="my-3 text-center">
      <%= f.submit "Add category", class: "btn btn-primary" %>
    </div>
  <% end %>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center">Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <div class="card mb-3">
      <div class="card-body">
        <div class="d-flex justify-content-between py-2">
          <h5 class="card-title"><%= fa_icon "#{category.icon}" %> <%= category.name %></h5>
          <p class="card-text"> <%= category.deals.map {|deal| deal.amount }.sum %>$</p>
        </div>
        <%= link_to "Show this category", category, class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New category", new_category_path, class: "category-button fixed-bottom"%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center"><%= @category.name.capitalize %>: <%= @category.deals.map {|deal| deal.amount }.sum %>$</h1>

<div id="category-deals">
  <% @category.deals.each do |category_deal| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= category_deal.name %></h5>
        <p class="card-text">Amount: <%= category_deal.amount %></p>
       <%= link_to "Show this transaction", "/categories/#{params[:id]}/deals/#{category_deal.id}" , class: "btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Add new deal", new_category_deal_path(params[:id]), class: "category-button"%>

app/views/deals/_deal.html.erb
<div id="<%= dom_id deal %>">
</div>

app/views/deals/_form.html.erb
<%= form_with url: category_deals_path do |form| %>
  <% if @deal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% @deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= bootstrap_form_with url: category_deals_path, scope: :deal do |f| %>
    <%= f.text_field :name, wrapper: { class: 'text-primary' } %>
    <%= f.text_field :amount, wrapper: { class: 'text-primary' } %>
    <%= f.collection_check_boxes :category_ids, @categories, :id, :name %>
    <div class="my-3 text-center">
      <%= f.submit "Add transaction", class: "btn btn-primary" %>
    </div>
  <% end %>

<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render "form", deal: @deal %>

<br>

<div>
  <%= link_to "Show this deal", @deal %> |
  <%= link_to "Back to deals", deals_path %>
</div>

app/views/deals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Deals</h1>

<div id="deals">
  <% @deals.each do |deal| %>
    <%= render deal %>
    <p>
      <%= link_to "Show this deal", deal %>
    </p>
  <% end %>
</div>

<%= link_to "New deal", new_deal_path %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render "form", deal: @deal %>

<br>

<div>
  <%= link_to "Back to deals", category_path(params[:category_id]) %>
</div>

app/views/deals/show.html.erb
<div>
    <h1> <%= @deal.name %> </h1>
    <h5><%= @deal.amount %></h5>
  <%= link_to "Back to home", categories_path, class: 'btn btn-dark mb-2' %>

  <%= button_to "Destroy this deal", category_deal_path(params[:category_id], @deal.id), method: :delete, class: 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<main class="d-flex flex-column align-center justify-content-center">
  <div class="showcase">
    <h1>Transaction calculator</h1>
  </div>
  <div class="register fixed-bottom w-100">
    <%= link_to 'Log In', new_user_session_path, class: "log-in" %>
    <%= link_to 'Sign Up', new_user_registration_path, class: "sign-up" %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetMobileApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_messages.html.erb
<% if notice %>
	<div class='alert alert-success alert-dismissible fade show' role="alert">
		<%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger alert-dismissible fade show' role="alert">
		<%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary static-top">
  <div class="container">
    <%= link_to ">", 'javascript:history.back()', class: "text-decoration-none back" %>
    <a class="navbar-brand" href="#">
      <%= image_tag("my-logo.png", height: 36) %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'My categories', categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My transactions', categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link text-light" %>
          </li>
        </ul>
        <% end %>
    </div>
  </div>
</nav>